In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str  
 1   company     892 non-null    str  
 2   year        892 non-null    str  
 3   Price       892 non-null    str  
 4   kms_driven  840 non-null    str  
 5   fuel_type   837 non-null    str  
dtypes: str(6)
memory usage: 41.9 KB


In [4]:
df.duplicated().value_counts()

False    798
True      94
Name: count, dtype: int64

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.duplicated().value_counts()

False    798
Name: count, dtype: int64

In [7]:
df['year'].unique()

<StringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [8]:
df['year'] = pd.to_numeric(df['year'],errors='coerce')

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 798 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        798 non-null    str    
 1   company     798 non-null    str    
 2   year        749 non-null    float64
 3   Price       798 non-null    str    
 4   kms_driven  748 non-null    str    
 5   fuel_type   745 non-null    str    
dtypes: float64(1), str(5)
memory usage: 43.6 KB


In [10]:
df['year'].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000.,   nan, 2003.,
       2004., 1995., 2002., 2001.])

In [11]:
df.dropna(subset=['year'],inplace=True)

In [12]:
df['year'] = df['year'].astype(int)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    str  
 1   company     749 non-null    str  
 2   year        749 non-null    int64
 3   Price       749 non-null    str  
 4   kms_driven  748 non-null    str  
 5   fuel_type   745 non-null    str  
dtypes: int64(1), str(5)
memory usage: 41.0 KB


In [14]:
df['Price'].unique()

<StringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 273, dtype: str

In [15]:
for i in df.index:
    Price = df.loc[i,'Price']
    Price = Price.replace(',','')
    df.loc[i,'Price'] = Price

In [16]:
df['Price'].unique()

<StringArray>
[        '80000',        '425000', 'Ask For Price',        '325000',
        '575000',        '175000',        '190000',        '830000',
        '250000',        '182000',
 ...
         '42000',        '189000',        '162000',         '35999',
       '2900000',         '39999',         '50500',        '510000',
        '860000',        '500001']
Length: 273, dtype: str

In [17]:
df['Price'] = pd.to_numeric(df['Price'],errors='coerce')

In [18]:
df['Price'].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  3400

In [19]:
df.dropna(subset=['Price'],inplace=True)

In [20]:
df['Price'].unique()

array([  80000.,  425000.,  325000.,  575000.,  175000.,  190000.,
        830000.,  250000.,  182000.,  315000.,  415000.,  320000.,
       1000000.,  500000.,  350000.,  160000.,  310000.,   75000.,
        100000.,  290000.,   95000.,  180000.,  385000.,  105000.,
        650000.,  689999.,  448000.,  549000.,  501000.,  489999.,
        280000.,  349999.,  284999.,  345000.,  499999.,  235000.,
        249999., 1475000.,  395000.,  220000.,  170000.,   85000.,
        200000.,  570000.,  110000.,  448999., 1891111.,  159500.,
        344999.,  449999.,  865000.,  699000.,  375000.,  224999.,
       1200000.,  195000.,  351000.,  240000.,   90000.,  155000.,
        600000.,  189500.,  210000.,  390000.,  135000., 1600000.,
        701000.,  265000.,  525000.,  372000.,  635000.,  550000.,
        485000.,  329500.,  251111.,  569999.,   69999.,  299999.,
        399999.,  450000.,  270000.,  158400.,  179000.,  125000.,
        299000.,  150000.,  275000.,  285000.,  340000.,   700

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 727 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        727 non-null    str    
 1   company     727 non-null    str    
 2   year        727 non-null    int64  
 3   Price       727 non-null    float64
 4   kms_driven  727 non-null    str    
 5   fuel_type   724 non-null    str    
dtypes: float64(1), int64(1), str(4)
memory usage: 39.8 KB


In [22]:
df['kms_driven'].unique()

<StringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
   '33,400 kms',   '60,123 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 250, dtype: str

In [23]:
for i in df.index:
    kms_driven = df.loc[i,'kms_driven']
    kms_driven = kms_driven.replace(',','')
    df.loc[i,'kms_driven'] = kms_driven

In [24]:
df['kms_driven'].unique()

<StringArray>
[ '45000 kms',     '40 kms',  '28000 kms',  '36000 kms',  '41000 kms',
  '25000 kms',  '24530 kms',  '60000 kms',  '30000 kms',  '32000 kms',
 ...
  '33400 kms',  '60123 kms', '137495 kms',  '91200 kms', '146000 kms',
 '100800 kms',   '2100 kms',   '2500 kms', '132000 kms',     'Petrol']
Length: 250, dtype: str

In [25]:
for i in df.index:
    kms_driven = df.loc[i,'kms_driven']
    kms_driven = kms_driven.replace('kms','')
    df.loc[i,'kms_driven'] = kms_driven

In [26]:
df['kms_driven'].unique()

<StringArray>
[ '45000 ',     '40 ',  '28000 ',  '36000 ',  '41000 ',  '25000 ',  '24530 ',
  '60000 ',  '30000 ',  '32000 ',
 ...
  '33400 ',  '60123 ', '137495 ',  '91200 ', '146000 ', '100800 ',   '2100 ',
   '2500 ', '132000 ',  'Petrol']
Length: 250, dtype: str

In [27]:
df['kms_driven'] = df['kms_driven'].str.strip()

In [28]:
df['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...  
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 727, dtype: str

In [29]:
df['kms_driven'] = pd.to_numeric(df['kms_driven'],errors='coerce')

In [30]:
df['kms_driven']

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...   
886    132000.0
888     27000.0
889     40000.0
890         NaN
891         NaN
Name: kms_driven, Length: 727, dtype: float64

In [31]:
df.dropna(subset='kms_driven',inplace=True)

In [33]:
df['kms_driven']

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...   
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 725, dtype: float64

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 725 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        725 non-null    str    
 1   company     725 non-null    str    
 2   year        725 non-null    int64  
 3   Price       725 non-null    float64
 4   kms_driven  725 non-null    float64
 5   fuel_type   724 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 39.6 KB


In [35]:
df['name'].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
             'Maruti Suzuki Stingray VXi',
 ...
                     'Mahindra Quanto C4',
              'Maruti Suzuki Swift Dzire',
             'Hyundai i20 Select Variant',
                   'Honda City VX Petrol',
                           'Hyundai Getz',
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
             'Maruti Suzuki Ritz VXI ABS',
              'Tata Indica V2 DLE BS III',
                    'Tata Zest XM Diesel']
Length: 463, dtype: str

In [37]:
for i in df.index:
    name = df.loc[i,'name']
    company = df.loc[i,'company']
    name = name.replace(company,"")
    df.loc[i,'name'] = name

In [38]:
df['name'] = df['name'].str.strip()

In [39]:
df['name'].unique()

<StringArray>
[  'Santro Xing XO eRLX Euro III',                 'Jeep CL550 MDI',
 'Grand i10 Magna 1.2 Kappa VTVT',    'EcoSport Titanium 1.5L TDCi',
                           'Figo',                            'Eon',
    'EcoSport Ambiente 1.5L TDCi',        'Suzuki Alto K10 VXi AMT',
          'Fabia Classic 1.2 MPI',            'Suzuki Stingray VXi',
 ...
                      'Quanto C4',             'Suzuki Swift Dzire',
             'i20 Select Variant',                 'City VX Petrol',
                           'Getz',          'Benz C Class 200 K MT',
                          'Fabia',            'Suzuki Ritz VXI ABS',
           'Indica V2 DLE BS III',                 'Zest XM Diesel']
Length: 463, dtype: str

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 725 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        725 non-null    str    
 1   company     725 non-null    str    
 2   year        725 non-null    int64  
 3   Price       725 non-null    float64
 4   kms_driven  725 non-null    float64
 5   fuel_type   724 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 55.8 KB


In [44]:
df.dropna(subset='fuel_type',inplace=True)

In [45]:
df.reset_index(drop=True,inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        724 non-null    str    
 1   company     724 non-null    str    
 2   year        724 non-null    int64  
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    float64
 5   fuel_type   724 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 34.1 KB


In [49]:
df['Price'].max()

np.float64(8500003.0)

In [53]:
df = (df[df['Price']<8500000.0])

In [54]:
df = (df[df['Price']>100000])

In [55]:
df['Price']

1      425000.0
2      325000.0
3      575000.0
4      175000.0
5      190000.0
         ...   
719    270000.0
720    110000.0
721    300000.0
722    260000.0
723    390000.0
Name: Price, Length: 635, dtype: float64

In [56]:
df = (df[df['kms_driven']>500])

In [59]:
df.reset_index(drop=True,inplace=True) 

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        621 non-null    str    
 1   company     621 non-null    str    
 2   year        621 non-null    int64  
 3   Price       621 non-null    float64
 4   kms_driven  621 non-null    float64
 5   fuel_type   621 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 29.2 KB


In [60]:
df.to_csv("clean_data.csv")

In [61]:
ds = pd.read_csv('clean_data.csv')
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  621 non-null    int64  
 1   name        621 non-null    str    
 2   company     621 non-null    str    
 3   year        621 non-null    int64  
 4   Price       621 non-null    float64
 5   kms_driven  621 non-null    float64
 6   fuel_type   621 non-null    str    
dtypes: float64(2), int64(2), str(3)
memory usage: 34.1 KB
